config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :users, only: [:new, :create, :show, :index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  get 'verify', to: 'users#verify', as: 'verify'
  post 'verify', to: 'users#verify'
  get 'register', to: 'users#new', as: 'register'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :phone_number, presence: true, uniqueness: true

  def to_json(options={})
    options[:except] ||= [:verified]
    super(options)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user = nil
    if session[:user_id]
      begin
        @current_user ||= User.find(session[:user_id])
      rescue ActiveRecord::RecordNotFound
      end
    else
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :current_user

  def index
    redirect_to login_path unless @current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password]) && user.verified
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    elsif user && user.authenticate(params[:password])
      redirect_to verify_url, notice: "You are not verified"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_client, only: [:create, :verify]
  before_action :current_user, only: [:verify]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    channel = user_params['channel']
    @user = User.new(user_params.except('channel', 'displayed_phone_number'))

    respond_to do |format|
      if @user.save
        start_verification(@user.phone_number, channel)
        session[:user_id] = @user.id
        format.html { redirect_to verify_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def verify
    if request.post?
      is_verified = check_verification(@current_user.phone_number, params['verification_code'])
      if is_verified
        @current_user.verified = true
        @current_user.save
        respond_to do |format|
          format.html { redirect_to main_index_url, notice: 'User was successfully verified.' }
        end
      else
        respond_to do |format|
          format.html { redirect_to verify_url, notice: 'The code was invalid.' }
        end
      end
    else
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_client
      @client = Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :phone_number)
    end

    def start_verification(to, channel='sms')
      channel = 'sms' unless ['sms', 'voice'].include? channel
      verification = @client.verify.services(ENV['VERIFICATION_SID'])
                                   .verifications
                                   .create(:to => to, :channel => channel)
      return verification.sid
    end

    def check_verification(phone, code)
      verification_check = @client.verify.services(ENV['VERIFICATION_SID'])
                                         .verification_checks
                                         .create(:to => phone, :code => code)
      return verification_check.status == 'approved'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> - Twilio Verify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta content="width=device-width, initial-scale=1" name="viewport" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <h1>Twilio Verify</h1>
      <ul>
        <li><%= link_to 'Register', register_path %></li>
        <li><%= link_to 'Log In', login_path %></li>
      </ul>
    </nav>
    <section class="content">
      <%= yield %>
    </section>
  </body>
</html>

app/views/main/index.html.erb
<% title "Secret Page" %>
<h1>Secret</h1>
<p>Welcome to the secret page <%= current_user.username %></p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :displayed_phone_number %>
    <%= form.text_field :displayed_phone_number, type: 'tel' %>
  </div>

  <div class="field">
    <label for="channel">Verification Method</label>
    <label><input type="radio" name="channel" value="sms" checked>SMS</label>
    <label><input type="radio" name="channel" value="voice">Call</label>
  </div>

  <div class="actions">
    <%= form.submit 'Sign Up' %>
  </div>
<% end %>


<script>
  var input = document.querySelector("#user_displayed_phone_number");
  window.intlTelInput(input, {
    hiddenInput: "phone_number",
    preferredCountries: ["us", "gb", "co", "de"]
  });
</script>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Phone number</th>
      <th>Verified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.verified %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% title 'Register' %>

<header><h1>Register</h1></header>

<%= render 'form', user: @user, except: [:verified] %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @user.verified %>
</p>

<%= link_to 'Back', users_path %>

app/views/users/verify.html.erb
<% title 'Verify' %>

<header><h1>Verify</h1></header>

<p id="notice"><%= notice %></p>

<%= form_tag(verify_url) do %>
  <div class="field">
    <%= label_tag :verification_code %>
    <%= text_field_tag :verification_code %>
  </div>

  <div class="actions">
    <%= submit_tag 'Verify' %>
  </div>
<% end %>


<%= link_to 'Back', users_path %>